### ISSUE TITLE
Client secret in facebook example app

### ISSUE THREAD

**Issue by Vosmik** [scrogson/oauth2_example#17]
Hi, thanks for this awesome library.

I was implementing Facebook strategy for phoenix API application. I needed to exchange code for an access_token and user info later.

I am not sure if I miss something or not, but shouldn't you put **client_secret** in **get_token** function in **Facebook strategy module** (I miss it in the example app). Something like this?

```
defmodule Facebook do
  .........

  def get_token(client, params, headers) do
      client
      **|> put_param(:client_secret, client.client_secret)**
      |> put_header("Accept", "application/json")
      |> AuthCode.get_token(params, headers)
    end
end
```

Or is it possible to have it straight inside **Oauth2.Strategy.Authcode** **get_token/3** ? Something like the one below? Are there any use cases where this might be a problem (accidentally exposing client_secret for different providers / situations)?

```
def get_token(client, params, headers) do
    {code, params} = Keyword.pop(params, :code, client.params["code"])

    unless code do
      raise OAuth2.Error, reason: "Missing required key `code` for `#{inspect __MODULE__}`"
    end

    client
    |> put_param(:code, code)
    |> put_param(:grant_type, "authorization_code")
    |> put_param(:client_id, client.client_id)
    **|> put_param(:client_secret, client.client_secret)**
    |> put_param(:redirect_uri, client.redirect_uri)
    |> merge_params(params)
    |> put_headers(headers)
  end
```

It took me some time to investigate this. It is just kind of misleading (at least for a newbie as I am). I thought that client_secret is already in client and there is no need to put it there again (and I didn`t see you added it somehow in the example app).

Thanks.

**Comment by scrogson** [comment]
Hi @Vosmik,

The short answer is that the `client_secret` should be added to the `Facebook` module. Pull-request welcome. 

It doesn't belong in the main OAuth2 library because that doesn't match the OAuth2 spec and causes some servers to error.

**Comment by Vosmik** [comment]
Great. I thought it could be something with Oauth specs. Once again, thanks for great library.
