### ISSUE TITLE
Can't install 'oauth2' dependency

### ISSUE THREAD

**Issue by ppold** [scrogson/oauth2_example#3]
When I try to do `mix deps.get` the following error appears:

*\* (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

**Comment by atbyrd** [comment]
I am getting the same error. I've tried using {:oauth2, "~> 0.0.3"} and  {:oauth2, github: "scrogson/oauth2"}

**Comment by jfpalngipang** [comment]
same error here.
